### ISSUE TITLE
Practicals available online?

### ISSUE THREAD

**Issue by jeiting** [oxford-cs-deepnlp-2017/lectures#6]
Just wondering if the materials for the practicals will be made available somewhere online for the public.

**Comment by jeiting** [comment]
Welp, I can self close this one. Thanks!
https://github.com/oxford-cs-deepnlp-2017/practical-open

**Comment by bshillingford** [comment]
I realize you found at least one of them and closed the issue, but there's also 3 others. I've added links to all 4 in the readme.
