### ISSUE TITLE
Lecture 9 in mp4?

### ISSUE THREAD

**Issue by akzaidi** [oxford-cs-deepnlp-2017/lectures#9]
Would it be possible to post lecture 9 in mp4 form as the other lectures?

Thanks!

**Comment by ghost** [comment]
You can download it by [youtube-dl](https://rg3.github.io/youtube-dl/):

```
youtube-dl 'https://ox.cloud.panopto.eu/Panopto/Pages/Viewer.aspx?id=790fad4d-fc9b-48e8-bd6c-d5efd9eb6663' -o '%(title)s.%(ext)s'
```

**Comment by bsc1780** [comment]
Yes sir thats fine.

**Comment by akzaidi** [comment]
awesome, thanks!
